- id: '1618991336207'
  alias: Home Assistant Restart Notification
  description: ''
  use_blueprint:
    path: gregoryduckworth/restart_notification.yaml
    input:
      notification_message: Home Assistant has successfully restarted!
      notify_device: 1ada3fdc6976622bd0226b539a5ccf25
- id: '1618991966165'
  alias: Home Assistant update notification
  description: ''
  use_blueprint:
    path: Klumper/update_notification.yaml
    input:
      notification_message: Home Assistant {{ newest_version }} is available
      delay: 0
      updater: binary_sensor.updater
      notify_device: 1ada3fdc6976622bd0226b539a5ccf25
      is_ios: false
- id: '1620159708446'
  alias: Обед закончился!
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.dinner_end
  condition: []
  action:
  - service: notify.lg_webos_smart_tv
    data:
      message: Обед заканчивается!
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: notify.lg_webos_smart_tv
    data:
      message: Обед закончился!
  - service: script.say_by_alice
    data:
      message: Обед закончился!
  mode: single
- id: '1620208571379'
  alias: Обед!
  description: ''
  trigger:
  - platform: event
    event_type: yandex_intent
    event_data:
      text: Обед
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.lg_webos_smart_tv
        state: 'off'
      sequence:
      - service: media_player.turn_on
        target:
          entity_id: media_player.lg_webos_smart_tv
    default: []
  - delay:
      hours: 0
      minutes: 0
      seconds: 13
      milliseconds: 0
  - service: timer.start
    data:
      duration: '0'
    target:
      entity_id: timer.dinner_end
  - service: media_player.select_source
    target:
      entity_id: media_player.lg_webos_smart_tv
    data:
      source: YouTube
  mode: single
- id: '1620222769842'
  alias: Алиса, Синхронизируй список покупок
  description: ''
  trigger:
  - platform: event
    event_type: yandex_intent
    event_data:
      text: Синхронизируй список покупок
  condition: []
  action:
  - service: script.1620222407435
  mode: single
- id: '1620741392513'
  alias: Управление перегревом большой подсветки
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states.sensor.temperatura_bolshoi_podsvetki.state | float(default=0)
      > 40 }}'
  - platform: state
    entity_id: input_boolean.upravlenie_peregrevom
  condition:
  - condition: state
    entity_id: input_boolean.upravlenie_peregrevom
    state: 'on'
  action:
  - service: light.turn_off
    target:
      entity_id: light.mqtt_lightentity_4
  mode: single
- id: '1621261422491'
  alias: Выключить музыку во время звонка телефона
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.oneplus_a5010_sostoianie_telefona
    to: ringing
  - platform: state
    entity_id: sensor.oneplus_a5010_sostoianie_telefona
    to: offhook
  condition:
  - condition: template
    value_template: '{{is_state(''person.imposibrus'', ''home'')}}'
  - condition: state
    entity_id: media_player.yandex_station_442078968308181c0410
    state: playing
  action:
  - service: var.set
    data:
      entity_id: var.yandex_station_volume
      value: '{{ state_attr(''media_player.yandex_station_442078968308181c0410'',
        ''volume_level'') }}'
  - service: media_player.volume_mute
    entity_id: media_player.yandex_station_442078968308181c0410
    data:
      is_volume_muted: true
  - wait_for_trigger:
    - platform: state
      entity_id: sensor.oneplus_a5010_sostoianie_telefona
      to: idle
    timeout: '300'
  - service: media_player.volume_set
    target:
      entity_id: media_player.yandex_station_442078968308181c0410
    data:
      volume_level: '{{ states(''var.yandex_station_volume'') }}'
  mode: single
- id: '1623060310948'
  alias: Работа!
  description: ''
  trigger:
  - platform: event
    event_type: yandex_intent
    event_data:
      text: Работа
  condition: []
  action:
  - scene: scene.rabota
  - service: script.say_by_alice
    data:
      message: Удачной охоты!
  mode: single
- id: '1623185538029'
  alias: Камин
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.kamin
    to: 'on'
  condition: []
  action:
  - service: script.kamin_mode
  mode: single
- id: '1623185896372'
  alias: Алиса - камин
  description: ''
  trigger:
  - platform: event
    event_type: yandex_intent
    event_data:
      text: Камин
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.kamin
  mode: single
- id: '1623522776112'
  alias: '[AC] На улице достаточно холодно, выключить кондиционер'
  description: ''
  trigger:
  - platform: state
    entity_id: climate.hisense_irhvac
    attribute: hvac_action
    to: cooling
  - platform: template
    value_template: '{{ (states(''sensor.gismeteo_temperature'') | float(default=0))
      < (states(''input_number.climate_temp_weather_ac_min'') | float(default=0))
      }}'
  condition:
  - condition: state
    entity_id: climate.hisense_irhvac
    attribute: hvac_action
    state: cooling
  - condition: template
    value_template: '{{ (states(''sensor.gismeteo_temperature'') | float(default=0))
      < (states(''input_number.climate_temp_weather_ac_min'') | float(default=0))
      }}'
  action:
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.hisense_irhvac
    data:
      hvac_mode: fan_only
  - service: notify.tg_home
    data:
      title: Кондиционер на проветривание
      message: На улице меньше {{ states('input_number.climate_temp_weather_ac_min')
        }}℃
      data:
        inline_keyboard:
        - Выключить:/AC_OFF, Охлаждение:/AC_COOL, Ок:/do_nothing
  mode: single
- id: '1623528326770'
  alias: '[AC] Включить кондиционер, когда кто-то приходит домой'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.template_anyone_home
    to: 'on'
    from: 'off'
  condition:
  - condition: state
    entity_id: climate.hisense_irhvac
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.cleargrass_air_temperature
    above: '26'
  action:
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.hisense_irhvac
    data:
      hvac_mode: cool
  - service: notify.tg_home
    data:
      title: Включаю кондиционер на охлаждение
      message: Кто-то пришел домой, когда было жарко
  mode: single
- id: '1624472919161'
  alias: '[AC] Включить кондиционер, когда жарко'
  description: ''
  trigger:
  - platform: state
    entity_id: climate.hisense_irhvac
    attribute: hvac_action
  - platform: template
    value_template: '{{ (states(''sensor.cleargrass_air_temperature'') | float(default=0))
      > (states(''input_number.climate_temp_max'') | float(default=0)) }}'
  condition:
  - condition: template
    value_template: '{{ state_attr(''climate.hisense_irhvac'', ''hvac_action'') !=
      ''cooling'' }}'
  - condition: template
    value_template: '{{ (states(''sensor.cleargrass_air_temperature'') | float(default=0))
      > (states(''input_number.climate_temp_max'') | float(default=0)) }}'
  - condition: state
    entity_id: binary_sensor.template_anyone_home
    state: 'on'
  action:
  - service: climate.set_hvac_mode
    target:
      entity_id: climate.hisense_irhvac
    data:
      hvac_mode: cool
  - service: notify.tg_home
    data:
      title: Включаю кондиционер на охлаждение
      message: Дома больше {{ states('input_number.climate_temp_max') }}℃
      data:
        inline_keyboard:
        - Выключи:/AC_OFF, На проветривание:/AC_VENTILATION, Ок:/do_nothing
  mode: single
- id: '1624479537110'
  alias: '[TG] Команда /do_nothing'
  description: ''
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: /do_nothing
  condition: []
  action:
  - service: telegram_bot.answer_callback_query
    data:
      message: Ок, игнор
      callback_query_id: '{{ trigger.event.data.id }}'
  - service: telegram_bot.delete_message
    data:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.chat_id }}'
  mode: single
- id: '1626280661780'
  alias: Вадим идет домой
  description: ''
  trigger:
  - platform: state
    entity_id: person.imposibrus
    from: Офис
    to: not_home
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    after: '18:30'
  action:
  - service: notify.tg_home
    data:
      title: Вадим вышел из офиса
      message: Ни дня не может без своей любимой😘
  mode: single
- id: '1627055594058'
  alias: '[TG] Команды кондиционера'
  description: ''
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: /AC_OFF
  - platform: event
    event_type: telegram_callback
    event_data:
      command: /AC_VENTILATION
  - platform: event
    event_type: telegram_callback
    event_data:
      command: /AC_COOL
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == ''/AC_VENTILATION'' }}'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.hisense_irhvac
        data:
          hvac_mode: fan_only
      - service: telegram_bot.answer_callback_query
        data:
          message: Кондиционер на проветривании!
          callback_query_id: '{{ trigger.event.data.id }}'
      - service: telegram_bot.delete_message
        data:
          chat_id: '{{ trigger.event.data.chat_id }}'
          message_id: '{{ trigger.event.data.message.message_id }}'
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == ''/AC_OFF'' }}'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.hisense_irhvac
        data:
          hvac_mode: 'off'
      - service: telegram_bot.answer_callback_query
        data:
          message: Кондиционер выключен!
          callback_query_id: '{{ trigger.event.data.id }}'
      - service: telegram_bot.delete_message
        data:
          chat_id: '{{ trigger.event.data.chat_id }}'
          message_id: '{{ trigger.event.data.message.message_id }}'
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == ''/AC_COOL'' }}'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.hisense_irhvac
        data:
          hvac_mode: cool
      - service: telegram_bot.answer_callback_query
        data:
          message: Кондиционер на охлаждение!
          callback_query_id: '{{ trigger.event.data.id }}'
      - service: telegram_bot.delete_message
        data:
          chat_id: '{{ trigger.event.data.chat_id }}'
          message_id: '{{ trigger.event.data.message.message_id }}'
    default: []
  mode: single
- id: '1638952855055'
  alias: Включить подсветку рабочего места утром
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.macbook_pro_active_2
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    before: '12:00'
    after: 07:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_on
    target:
      entity_id: light.mqtt_lightentity_4
  mode: single
- id: '1644352009872'
  alias: Включение ТВ
  description: ''
  trigger:
  - platform: webostv.turn_on
    entity_id: media_player.lg_webos_smart_tv
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.lg_tv
  mode: single
