- id: '1618991336207'
  alias: Home Assistant Restart Notification
  description: ''
  use_blueprint:
    path: gregoryduckworth/restart_notification.yaml
    input:
      notification_message: Home Assistant has successfully restarted!
      notify_device: 1ada3fdc6976622bd0226b539a5ccf25
- id: '1618991966165'
  alias: Home Assistant update notification
  description: ''
  use_blueprint:
    path: Klumper/update_notification.yaml
    input:
      notification_message: Home Assistant {{ newest_version }} is available
      delay: 0
      updater: binary_sensor.updater
      notify_device: 1ada3fdc6976622bd0226b539a5ccf25
      is_ios: false
- id: '1620159708446'
  alias: Обед закончился!
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.dinner_end
  condition: []
  action:
  - service: notify.lg_webos_smart_tv
    data:
      message: Обед заканчивается!
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: notify.lg_webos_smart_tv
    data:
      message: Обед закончился!
  - service: script.say_by_alice
    data:
      message: Обед закончился!
  mode: single
- id: '1620208571379'
  alias: Обед!
  description: ''
  trigger:
  - platform: event
    event_type: yandex_intent
    event_data:
      text: Обед
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.lg_webos_smart_tv
        state: 'off'
      sequence:
      - service: media_player.turn_on
        target:
          entity_id: media_player.lg_webos_smart_tv
    default: []
  - delay:
      hours: 0
      minutes: 0
      seconds: 13
      milliseconds: 0
  - service: timer.start
    data:
      duration: '0'
    target:
      entity_id: timer.dinner_end
  - service: media_player.select_source
    target:
      entity_id: media_player.lg_webos_smart_tv
    data:
      source: YouTube
  mode: single
- id: '1620222769842'
  alias: Алиса, Синхронизируй список покупок
  description: ''
  trigger:
  - platform: event
    event_type: yandex_intent
    event_data:
      text: Синхронизируй список покупок
  condition: []
  action:
  - service: script.1620222407435
  mode: single
- id: '1620741392513'
  alias: Управление перегревом большой подсветки
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states.sensor.temperatura_bolshoi_podsvetki.state | float
      > 40 }}'
  - platform: state
    entity_id: input_boolean.upravlenie_peregrevom
  condition:
  - condition: state
    entity_id: input_boolean.upravlenie_peregrevom
    state: 'on'
  action:
  - service: light.turn_off
    target:
      entity_id: light.mqtt_lightentity_4
  mode: single
- id: '1621261422491'
  alias: Выключить музыку во время звонка телефона
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.oneplus_a5010_sostoianie_telefona
    to: ringing
  - platform: state
    entity_id: sensor.oneplus_a5010_sostoianie_telefona
    to: offhook
  condition:
  - condition: template
    value_template: '{{is_state(''person.imposibrus'', ''home'')}}'
  - condition: state
    entity_id: media_player.yandex_station_442078968308181c0410
    state: playing
  action:
  - service: var.set
    data:
      entity_id: var.yandex_station_volume
      value: '{{ state_attr(''media_player.yandex_station_442078968308181c0410'',
        ''volume_level'') }}'
  - service: media_player.volume_mute
    entity_id: media_player.yandex_station_442078968308181c0410
    data:
      is_volume_muted: true
  - wait_for_trigger:
    - platform: state
      entity_id: sensor.oneplus_a5010_sostoianie_telefona
      to: idle
    timeout: '300'
  - service: media_player.volume_set
    target:
      entity_id: media_player.yandex_station_442078968308181c0410
    data:
      volume_level: '{{ states(''var.yandex_station_volume'') }}'
  mode: single
- id: '1623060310948'
  alias: Работа!
  description: ''
  trigger:
  - platform: event
    event_type: yandex_intent
    event_data:
      text: Работа
  condition: []
  action:
  - scene: scene.rabota
  - service: script.say_by_alice
    data:
      message: Удачной охоты!
  mode: single
- id: '1623185538029'
  alias: Камин
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.kamin
    to: 'on'
  condition: []
  action:
  - service: script.kamin_mode
  mode: single
- id: '1623185896372'
  alias: Алиса - камин
  description: ''
  trigger:
  - platform: event
    event_type: yandex_intent
    event_data:
      text: Камин
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.kamin
  mode: single
- id: '1623522776112'
  alias: На улице достаточно холодно. Выключим кондиционер?
  description: ''
  trigger:
  - platform: state
    entity_id: climate.hisense_irhvac
    attribute: hvac_action
    to: cooling
  - platform: numeric_state
    entity_id: sensor.gismeteo_temperature
    below: '20'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: climate.hisense_irhvac
      attribute: hvac_action
      state: cooling
    - condition: numeric_state
      entity_id: sensor.gismeteo_temperature
      below: '20'
  action:
  - service: notify.mobile_app_oneplus_a5010
    data:
      title: На улице меньше 20℃
      message: Пора выключить кондиционер
      data:
        actions:
        - action: AC_TURN_OFF
          title: Выключить
        - action: AC_VENTILATION
          title: Вентиляция
  - wait_for_trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: AC_TURN_OFF
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: AC_VENTILATION
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ wait.trigger.event.data.action == ''AC_TURN_OFF'' }}'
      sequence:
      - service: climate.turn_off
        target:
          entity_id: climate.hisense_irhvac
    - conditions:
      - condition: template
        value_template: '{{ wait.trigger.event.data.action == ''AC_VENTILATION'' }}'
      sequence:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.hisense_irhvac
        data:
          hvac_mode: fan_only
    default: []
  mode: single
  variables:
    action_turn_off: '{{ ''AC_TURN_OFF_'' ~ context.id }}'
    action_ventilation: '{{ ''AC_VENTILATION_'' ~ context.id }}'
