
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logbook:
  exclude:
    domains:
      - air_quality
    entity_globs:
      - binary_sensor.oneplus_a5010*

yandex_station:
  username: !secret yandex_username
  password: !secret yandex_password
  recognition_lang: ru-RU
  devices:
    442078968308181c0410:
      host: !secret yandex_station_ip
  intents:
    Обед:
    Синхронизируй список покупок:
  include:
    - Телевизор
    - Кондиционер

conversation:
  intents:
    media_player.yandex_station_442078968308181c0410: [.+]

yandex_smart_home:
  notifier:
    oauth_token: !secret yandex_oauth_token
    skill_id: !secret yandex_skill_id
    user_id: !secret yandex_user_id
  settings:
    pressure_unit: mmHg
  filter:
    include_entities:
      - sensor.cgllc_airmonitor_s1
    exclude_entities:
      - media_player.yandex_station_442078968308181c0410
      - media_player.televizor
      - media_player.televizor_2
      - media_player.lg_webos_smart_tv
      - sensor.oneplus_a5010_battery_temperature
    exclude_domains:
      - scene
      - script
  entity_config:
    sensor.cgllc_airmonitor_s1:
      type: devices.types.sensor
      properties:
        - type: temperature
          entity: sensor.cleargrass_air_temperature
        - type: humidity
          entity: sensor.cleargrass_air_humidity

lovelace:
  resources:
    - url: /hacsfiles/ha-yandex-icons/yandex-icons.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js?v=1.11.0
      type: module

sensor:
  - platform: google_fit
    name: imposibrus
    client_id: !secret google_fit_client_id
    client_secret: !secret google_fit_client_secret

  - platform: template
    sensors:
      cleargrass_air_co2:
        friendly_name: 'CO2'
        value_template: "{{ state_attr('air_quality.cgllc_airmonitor_s1', 'carbon_dioxide') }}"
        icon_template: mdi:molecule-co2
        unique_id: 'cleargrass_air_co2'
        unit_of_measurement: 'ppm'

      cleargrass_air_tvoc:
        friendly_name: 'tVOC'
        value_template: "{{ ((state_attr('air_quality.cgllc_airmonitor_s1', 'total_volatile_organic_compounds') | float * 4.5) / 1000) | round(3) }}"
        icon_template: mdi:alpha-t
        unique_id: 'cleargrass_air_tvoc'
        unit_of_measurement: 'mg/m³'

      cleargrass_air_pm25:
        friendly_name: 'PM2.5'
        value_template: "{{ state_attr('air_quality.cgllc_airmonitor_s1', 'particulate_matter_2_5') }}"
        icon_template: mdi:alpha-p
        unique_id: 'cleargrass_air_pm25'
        unit_of_measurement: 'μg/m³'

      cleargrass_air_temperature:
        friendly_name: 'Temperature'
        value_template: "{{ state_attr('air_quality.cgllc_airmonitor_s1', 'temperature') }}"
        icon_template: mdi:temperature-celsius
        unique_id: 'cleargrass_air_temperature'
        unit_of_measurement: '°C'

      cleargrass_air_humidity:
        friendly_name: 'Humidity'
        value_template: "{{ state_attr('air_quality.cgllc_airmonitor_s1', 'humidity') }}"
        icon_template: mdi:water-percent
        unique_id: 'cleargrass_air_humidity'
        unit_of_measurement: '%'

light:
  - platform: mqtt
    unique_id: 'wb-mr6c_42/K3'
    command_topic: '/devices/wb-mr6c_42/controls/K3/on'
    payload_on: 1
    payload_off: 0

  - platform: mqtt
    unique_id: 'wb-mr6c_138/K1'
    command_topic: '/devices/wb-mr6c_138/controls/K1/on'
    payload_on: 1
    payload_off: 0

  - platform: mqtt
    unique_id: 'wb-mdm3_104/K1'
    state_topic: '/devices/wb-mdm3_104/controls/K1'
    command_topic: '/devices/wb-mdm3_104/controls/K1/on'
    brightness_state_topic: '/devices/wb-mdm3_104/controls/Channel 1'
    brightness_command_topic: '/devices/wb-mdm3_104/controls/Channel 1/on'
    brightness_scale: 100
    payload_on: 1
    payload_off: 0

  - platform: mqtt
    unique_id: 'wb-mrgbw-d_153/White 3-G'
    state_topic: '/devices/wb-mrgbw-d_153/controls/White 3-G/state'
    command_topic: '/devices/wb-mrgbw-d_153/controls/White 3-G/set'
    brightness_state_topic: '/devices/wb-mrgbw-d_153/controls/White 3-G'
    brightness_command_topic: '/devices/wb-mrgbw-d_153/controls/White 3-G/on'
    payload_on: 1
    payload_off: 0

  - platform: mqtt
    unique_id: 'wb-mrgbw-d_153/White 4-W'
    state_topic: '/devices/wb-mrgbw-d_153/controls/White 4-W/state'
    command_topic: '/devices/wb-mrgbw-d_153/controls/White 4-W/set'
    brightness_state_topic: '/devices/wb-mrgbw-d_153/controls/White 4-W'
    brightness_command_topic: '/devices/wb-mrgbw-d_153/controls/White 4-W/on'
    payload_on: 1
    payload_off: 0

webostv:
  host: !secret webostv_host

timer:
  dinner_end:
    duration: '00:50:00'

mqtt_statestream:
  base_topic: homeassistant
  publish_attributes: true
  publish_timestamps: true

#climate:
#  - platform: tasmota_irhvac
#    name: Hisense IRHvac
#    command_topic: "cmnd/tasmota_31E9B1/irhvac"
#    state_topic: "tele/tasmota_31E9B1/RESULT"
#    temperature_sensor: sensor.cleargrass_air_temperature #optional this sensor is used to display current temp on the AC card
#    protocol: "WHIRLPOOL_AC"
#    min_temp: 16 #optional - default 16 int value
#    max_temp: 30 #optional - default 32 int value
#    target_temp: 25 #optional - default 26 int value
#    initial_operation_mode: "off" # optional - default "off" string value
#    away_temp: 24 #optional - default 24 int value
#    precision: 1.0 #optional - default 1.0 float value
#    supported_modes:
#      - heat
#      - cool
#      - dry
#      - fan_only
#      - auto
#      - "off" #Turns the AC off - Should be quoted and should be always included here
#    supported_fan_speeds:
#      #- low
#      - max
#      - medium
#      # - high
#      #- middle
#      #- focus
#      #- diffuse
#      - min
#      - auto
#    supported_swing_list:
#      - "off"
#      - vertical #up to down
#      - horizontal # Left to right - remove if your AC does not support it
#      - both # remove if your AC does not support horizontal
#    hvac_model: "2" # string value
#    celsius_mode: "On" #optional - default "On" string value - you can remove it if you use celsius



group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
