
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
#cloud:
config:
counter:
dhcp:
history:
image:
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
map:
#media_source:
mobile_app:
my:
person:
ssdp:
stream:
sun:
system_health:
tag:
timer:
#updater:
zeroconf:
zone:

frontend:
  themes: !include_dir_merge_named themes/

recorder:
  purge_keep_days: 20

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.88.0/24

homeassistant:
  packages: !include_dir_merge_named includes/packages/
  customize: !include customize.yaml

lovelace:
  resources:
    - url: /hacsfiles/ha-yandex-icons/yandex-icons.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js?v=1.11.0
      type: module

browser_mod:
  prefix: "browser_"
  devices:
    68f87c9e-0545f5a0:
      name: 'Chrome Macbook'

  disable:
    - all

logger:
  default: warning
#  logs:
#    homeassistant.components.ble_monitor: debug
#    custom_components.ble_monitor: debug

logbook: !include includes/logbook.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

