
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
application_credentials:
backup:
#cloud:
config:
counter:
dhcp:
#energy:
history:
image:
input_boolean:
input_button:
input_datetime:
input_number:
input_select:
input_text:
map:
media_source:
mobile_app:
my:
network:
person:
schedule:
ssdp:
stream:
sun:
system_health:
tag:
timer:
#usb:
webhook:
zeroconf:
zone:

frontend:
  themes: !include_dir_merge_named themes/

recorder:
  purge_keep_days: 20

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.88.0/24

homeassistant:
  packages: !include_dir_merge_named includes/packages/
  customize: !include customize.yaml

lovelace:
  resources:
    - url: /hacsfiles/ha-yandex-icons/yandex-icons.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js?v=1.11.0
      type: module

logger:
  default: warning
  logs:
#    custom_components.xiaomi_miot: debug
    custom_components.ble_monitor: info

logbook: !include includes/logbook.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

