
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
#cloud:
config:
counter:
dhcp:
frontend:
history:
image:
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
logbook:
#map:
#media_source:
mobile_app:
my:
person:
ssdp:
stream:
sun:
system_health:
tag:
timer:
updater:
zeroconf:
zone:

homeassistant:
  packages: !include_dir_merge_named includes/packages/

lovelace:
  resources:
    - url: /hacsfiles/ha-yandex-icons/yandex-icons.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js?v=1.11.0
      type: module

webostv:
  host: !secret webostv_host

logbook: !include includes/logbook.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

