version: '3'
services:
  home-assistant:
    image: 'homeassistant/home-assistant:2023.6.1'
    restart: always
    container_name: 'home-assistant'
    network_mode: host
    volumes:
      - ./:/config
    environment:
      - 'TZ=Europe/Moscow'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.homeassistant-secure.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.homeassistant-secure.tls.certresolver=default"
      - "traefik.http.routers.homeassistant-secure.service=homeassistant"
      - "traefik.http.routers.homeassistant-secure.middlewares=sslheader@file"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"


