version: '3'
services:
  home-assistant:
    image: 'homeassistant/home-assistant:2023.1.7'
    restart: always
    container_name: 'home-assistant'
    network_mode: host
#    ports:
#      - 8123:8123
    volumes:
      - ./:/config
    environment:
      - 'TZ=Europe/Moscow'

